export const languageMap = {
  en: 'Column1',
  zh_TW: 'Column7',
  zh_CN: 'Column9',
  pt_BR: 'Column11',
  en_US: 'Column13',
  de: 'Column15',
  es: 'Column17',
  fr: 'Column19',
  it: 'Column21',
  ja: 'Column23',
  ko: 'Column25',
  da: 'Column29',
  sv: 'Column31',
  no: 'Column33',
  nl_NL: 'Column35',
  es_MX: 'Column37',
}
